spring:
  application:
    name: jobs-service
  config:
    import: optional:configserver:http://config-server:8888/
  profiles:
    active: docker
  cloud:
    config:
      uri: http://config-server:8888

review-service:
  url: http://review:8083
company-service:
  url: http://company:8081