services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: jhunter
      POSTGRES_PASSWORD: patrick
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - jhunter-net
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - jhunter-net
    restart: unless-stopped
  config-server:
    image: patrickdevcoffee/config-server:latest
    container_name: config-server
    ports:
      - 8888:8888
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - jhunter-net


  servicereg:
    image: patrickdevcoffee/servicereg:latest
    container_name: servicereg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - jhunter-net

  companyms:
    image: patrickdevcoffee/companyms:latest
    container_name: company
    ports:
      - 8081:8081
    depends_on:
      - servicereg
      - config-server
    networks:
      - microservice-network
      - jhunter-net
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_APPLICATION_NAME=company-service
      - SPRING_PROFILES_ACTIVE=docker  # Optional
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  jobms:
    image: patrickdevcoffee/jobsms:latest
    container_name: jobs
    ports:
      - 8082:8082
    depends_on:
      - servicereg
      - config-server
    networks:
      - microservice-network
      - jhunter-net
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_APPLICATION_NAME=jobs-service
      - SPRING_PROFILES_ACTIVE=docker  # Optional
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  reviewms:
    image: patrickdevcoffee/reviewms:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - servicereg
      - config-server
    networks:
      - microservice-network
      - jhunter-net
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_APPLICATION_NAME=review-service
      - SPRING_PROFILES_ACTIVE=docker  # Optional
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
  gateway-ms:
    image: patrickdevcoffee/gateway-ms:latest
    ports:
      - 8085:8085
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - jhunter-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - jhunter-net
    restart: unless-stopped
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - jhunter-net
    restart: unless-stopped
networks:
  microservice-network:
    driver: bridge
  jhunter-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
