spring:
  application:
    name: review-service
  config:
    import: optional:configserver:http://config-server:8888/
  profiles:
    active: docker
  cloud:
    config:
      uri: http://config-server:8888
company-service:
  url: http://company:8081/